/// Flutter icons AtcIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AtcIcons
///      fonts:
///       - asset: fonts/AtcIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AtcIcons {
  AtcIcons._();

  static const _kFontFam = 'AtcIcons';
  static const _kFontPkg = null;

  static const IconData search_menu_on =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search_menu_off =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saved_menu_on =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData saved_menu_off =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_menu_on =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more_menu_off =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_menu_on =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_menu_off =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
